# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [1]:
import pandas as pd

## imports for Python, Pandas

In [2]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [3]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [4]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [5]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [6]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

[{'_id': {'$oid': '52b213b38594d8a2be17c780'},
  'approvalfy': 1999,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-12T00:00:00Z',
  'borrower': 'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA',
  'closingdate': '2018-07-07T00:00:00Z',
  'country_namecode': 'Federal Democratic Republic of Ethiopia!$!ET',
  'countrycode': 'ET',
  'countryname': 'Federal Democratic Republic of Ethiopia',
  'countryshortname': 'Ethiopia',
  'docty': 'Project Information Document,Indigenous Peoples Plan,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 0,
  'ibrdcommamt': 0,
  'id': 'P129828',
  'idacommamt': 130000000,
  'impagency': 'MINISTRY OF EDUCATION',
  'lendinginstr': 'Investment Project Financing',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 550000000,
  'majorsector_percent': [{'Name': 'Education', 'Percent': 46},
   {'Name': 'Education', 'Percent': 26},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 16},
   {'Name': 'Education', 'Percent': 12}],
  'mjsector_namecode': [{'code': 'EX', 'name': 'Education'},
   {'code': 'EX', 'name': 'Education'},
   {'code': 'BX', 'name': 'Public Administration, Law, and Justice'},
   {'code': 'EX', 'name': 'Education'}],
  'mjtheme': ['Human development'],
  'mjtheme_namecode': [{'code': '8', 'name': 'Human development'},
   {'code': '11', 'name': ''}],
  'mjthemecode': '8,11',
  'prodline': 'PE',
  'prodlinetext': 'IBRD/IDA',
  'productlinetype': 'L',
  'project_abstract': {'cdata': 'The development objective of the Second Phase of General Education Quality Improvement Project for Ethiopia is to improve learning conditions in primary and secondary schools and strengthen institutions at different levels of educational administration. The project has six components. The first component is curriculum, textbooks, assessment, examinations, and inspection. This component will support improvement of learning conditions in grades KG-12 by providing increased access to teaching and learning materials and through improvements to the curriculum by assessing the strengths and weaknesses of the current curriculum. This component has following four sub-components: (i) curriculum reform and implementation; (ii) teaching and learning materials; (iii) assessment and examinations; and (iv) inspection. The second component is teacher development program (TDP). This component will support improvements in learning conditions in both primary and secondary schools by advancing the quality of teaching in general education through: (a) enhancing the training of pre-service teachers in teacher education institutions; and (b) improving the quality of in-service teacher training. This component has following three sub-components: (i) pre-service teacher training; (ii) in-service teacher training; and (iii) licensing and relicensing of teachers and school leaders. The third component is school improvement plan. This component will support the strengthening of school planning in order to improve learning outcomes, and to partly fund the school improvement plans through school grants. It has following two sub-components: (i) school improvement plan; and (ii) school grants. The fourth component is management and capacity building, including education management information systems (EMIS). This component will support management and capacity building aspect of the project. This component has following three sub-components: (i) capacity building for education planning and management; (ii) capacity building for school planning and management; and (iii) EMIS. The fifth component is improving the quality of learning and teaching in secondary schools and universities through the use of information and communications technology (ICT). It has following five sub-components: (i) national policy and institution for ICT in general education; (ii) national ICT infrastructure improvement plan for general education; (iii) develop an integrated monitoring, evaluation, and learning system specifically for the ICT component; (iv) teacher professional development in the use of ICT; and (v) provision of limited number of e-Braille display readers with the possibility to scale up to all secondary education schools based on the successful implementation and usage of the readers. The sixth component is program coordination, monitoring and evaluation, and communication. It will support institutional strengthening by developing capacities in all aspects of program coordination, monitoring and evaluation; a new sub-component on communications will support information sharing for better management and accountability. It has following three sub-components: (i) program coordination; (ii) monitoring and evaluation (M and E); and (iii) communication.'},
  'project_name': 'Ethiopia General Education Quality Improvement Project II',
  'projectdocs': [{'DocDate': '28-AUG-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b081e545fb_1_0',
    'EntityID': '090224b081e545fb_1_0'},
   {'DocDate': '01-JUL-2013',
    'DocType': 'IP',
    'DocTypeDesc': 'Indigenous Peoples Plan (IP),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20130920111729',
    'EntityID': '000442464_20130920111729'},
   {'DocDate': '22-NOV-2012',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b0817b19e2_1_0',
    'EntityID': '090224b0817b19e2_1_0'}],
  'projectfinancialtype': 'IDA',
  'projectstatusdisplay': 'Active',
  'regionname': 'Africa',
  'sector': [{'Name': 'Primary education'},
   {'Name': 'Secondary education'},
   {'Name': 'Public administration- Other social services'},
   {'Name': 'Tertiary education'}],
  'sector1': {'Name': 'Primary education', 'Percent': 46},
  'sector2': {'Name': 'Secondary education', 'Percent': 26},
  'sector3': {'Name': 'Public administration- Other social services',
   'Percent': 16},
  'sector4': {'Name': 'Tertiary education', 'Percent': 12},
  'sector_namecode': [{'code': 'EP', 'name': 'Primary education'},
   {'code': 'ES', 'name': 'Secondary education'},
   {'code': 'BS', 'name': 'Public administration- Other social services'},
   {'code': 'ET', 'name': 'Tertiary education'}],
  'sectorcode': 'ET,BS,ES,EP',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Education for all', 'Percent': 100},
  'theme_namecode': [{'code': '65', 'name': 'Education for all'}],
  'themecode': '65',
  'totalamt': 130000000,
  'totalcommamt': 130000000,
  'url': 'http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en'},
 {'_id': {'$oid': '52b213b38594d8a2be17c781'},
  'approvalfy': 2015,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-04T00:00:00Z',
  'borrower': 'GOVERNMENT OF TUNISIA',
  'country_namecode': 'Republic of Tunisia!$!TN',
  'countrycode': 'TN',
  'countryname': 'Republic of Tunisia',
  'countryshortname': 'Tunisia',
  'docty': 'Project Information Document,Integrated Safeguards Data Sheet,Integrated Safeguards Data Sheet,Project Information Document,Integrated Safeguards Data Sheet,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 4700000,
  'ibrdcommamt': 0,
  'id': 'P144674',
  'idacommamt': 0,
  'impagency': 'MINISTRY OF FINANCE',
  'lendinginstr': 'Specific Investment Loan',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 5700000,
  'majorsector_percent': [{'Name': 'Public Administration, Law, and Justice',
    'Percent': 70},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 30}],
  'mjsector_namecode': [{'code': 'BX',
    'name': 'Public Administration, Law, and Justice'},
   {'code': 'BX', 'name': 'Public Administration, Law, and Justice'}],
  'mjtheme': ['Economic management', 'Social protection and risk management'],
  'mjtheme_namecode': [{'code': '1', 'name': 'Economic management'},
   {'code': '6', 'name': 'Social protection and risk management'}],
  'mjthemecode': '1,6',
  'prodline': 'RE',
  'prodlinetext': 'Recipient Executed Activities',
  'productlinetype': 'L',
  'project_name': 'TN: DTF Social Protection Reforms Support',
  'projectdocs': [{'DocDate': '29-MAR-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131024115616',
    'EntityID': '000333037_20131024115616'},
   {'DocDate': '29-MAR-2013',
    'DocType': 'ISDS',
    'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20131024151611',
    'EntityID': '000356161_20131024151611'},
   {'DocDate': '29-MAR-2013',
    'DocType': 'ISDS',
    'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20131031112136',
    'EntityID': '000442464_20131031112136'},
   {'DocDate': '29-MAR-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131031105716',
    'EntityID': '000333037_20131031105716'},
   {'DocDate': '16-JAN-2013',
    'DocType': 'ISDS',
    'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113209',
    'EntityID': '000356161_20130305113209'},
   {'DocDate': '16-JAN-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113716',
    'EntityID': '000356161_20130305113716'}],
  'projectfinancialtype': 'OTHER',
  'projectstatusdisplay': 'Active',
  'regionname': 'Middle East and North Africa',
  'sector': [{'Name': 'Public administration- Other social services'},
   {'Name': 'General public administration sector'}],
  'sector1': {'Name': 'Public administration- Other social services',
   'Percent': 70},
  'sector2': {'Name': 'General public administration sector', 'Percent': 30},
  'sector_namecode': [{'code': 'BS',
    'name': 'Public administration- Other social services'},
   {'code': 'BZ', 'name': 'General public administration sector'}],
  'sectorcode': 'BZ,BS',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Other economic management', 'Percent': 30},
  'theme_namecode': [{'code': '24', 'name': 'Other economic management'},
   {'code': '54', 'name': 'Social safety nets'}],
  'themecode': '54,24',
  'totalamt': 0,
  'totalcommamt': 4700000,
  'url': 'http://www.worldbank.org/projects/P144674?lang=en'}]

In [7]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Name': 'Education for all', 'Percent': 100}","[{'name': 'Education for all', 'code': '65'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Name': 'Other economic management', 'Percent...","[{'name': 'Other economic management', 'code':...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [8]:
df = pd.read_json('data/world_bank_projects.json')
df.shape

(500, 50)

## Exercise 1: 10 countries with most projects

In [9]:
projects_counts = df.countrycode.value_counts()
print(projects_counts.head(10))

CN    19
ID    19
VN    17
IN    16
RY    13
MA    12
NP    12
BD    12
MZ    11
3A    11
Name: countrycode, dtype: int64

## Exercise 2:  find 10 major project theme

In [10]:
df[['mjtheme', 'mjtheme_namecode', 'mjthemecode']]

,mjtheme,mjtheme_namecode,mjthemecode
0,[Human development],"[{'code': '8', 'name': 'Human development'}, {...","8,11"
1,"[Economic management, Social protection and ri...","[{'code': '1', 'name': 'Economic management'},...","1,6"
2,"[Trade and integration, Public sector governan...","[{'code': '5', 'name': 'Trade and integration'...","5,2,11,6"
3,"[Social dev/gender/inclusion, Social dev/gende...","[{'code': '7', 'name': 'Social dev/gender/incl...","7,7"
4,"[Trade and integration, Financial and private ...","[{'code': '5', 'name': 'Trade and integration'...","5,4"
5,[Social protection and risk management],"[{'code': '6', 'name': 'Social protection and ...","6,6"
6,"[Public sector governance, Financial and priva...","[{'code': '2', 'name': 'Public sector governan...","2,4"
7,[Environment and natural resources management],"[{'code': '11', 'name': 'Environment and natur...","11,8"
8,[Rural development],"[{'code': '10', 'name': 'Rural development'}, ...","10,7"
9,"[Public sector governance, Public sector gover...","[{'code': '2', 'name': 'Public sector governan...","2,2,2"
10,[Rural development],"[{'code': '10', 'name': 'Rural development'}, ...","10,2"
11,"[Rural development, Social protection and risk...","[{'code': '10', 'name': 'Rural development'}, ...","10,6,6,11"
12,NaN,"[{'code': '4', 'name': ''}]",4
13,"[Trade and integration, Environment and natura...","[{'code': '5', 'name': 'Trade and integration'...","5,11,10"
14,"[Social protection and risk management, Social...","[{'code': '6', 'name': 'Social protection and ...","6,6,6"
15,"[Rural development, Environment and natural re...","[{'code': '10', 'name': 'Rural development'}, ...","10,11,5"
16,[Rural development],"[{'code': '10', 'name': 'Rural development'}, ...","10,2"
17,[Human development],"[{'code': '8', 'name': 'Human development'}, {...","8,7"
18,"[Human development, Human development, Public ...","[{'code': '8', 'name': 'Human development'}, {...","8,8,2,7,8"
19,"[Public sector governance, Public sector gover...","[{'code': '2', 'name': 'Public sector governan...","2,2,2"
20,"[Social dev/gender/inclusion, Social dev/gende...","[{'code': '7', 'name': 'Social dev/gender/incl...","7,7"
21,"[Urban development, Social dev/gender/inclusion]","[{'code': '9', 'name': 'Urban development'}, {...","9,7"
22,"[Social dev/gender/inclusion, Social dev/gende...","[{'code': '7', 'name': 'Social dev/gender/incl...","7,7"
23,"[Human development, Human development]","[{'code': '8', 'name': 'Human development'}, {...","8,8"
24,"[Rural development, Rural development, Rural d...","[{'code': '10', 'name': 'Rural development'}, ...","10,10,10,6"
25,"[Environment and natural resources management,...","[{'code': '11', 'name': 'Environment and natur...","11,11,11"
26,"[Financial and private sector development, Tra...","[{'code': '4', 'name': 'Financial and private ...","4,5,2,8"
27,"[Environment and natural resources management,...","[{'code': '11', 'name': 'Environment and natur...","11,2,5,6"
28,"[Rural development, Rural development, Social ...","[{'code': '10', 'name': 'Rural development'}, ...","10,10,7"
29,"[Social dev/gender/inclusion, Environment and ...","[{'code': '7', 'name': 'Social dev/gender/incl...","7,11"
...,...,...,...
470,"[Trade and integration, Rural development]","[{'code': '5', 'name': 'Trade and integration'...","5,10"
471,"[Rural development, Social dev/gender/inclusio...","[{'code': '10', 'name': 'Rural development'}, ...","10,7,11,7"
472,[Environment and natural resources management],"[{'code': '11', 'name': 'Environment and natur...","11,11"
473,[Environment and natural resources management],"[{'code': '11', 'name': 'Environment and natur...","11,4"
474,"[Urban development, Urban development]","[{'code': '9', 'name': 'Urban development'}, {...","9,9"
475,"[Financial and private sector development, Urb...","[{'code': '4', 'name': 'Financial and private ...","4,9"
476,[Rural development],"[{'code': '10', 'name': 'Rural development'}, ...","10,8"
477,"[Financial and private sector development, Rur...","[{'code': '4', 'name': 'Financial and private ...","4,10"
478,"[Public sector governance, Rule of law, Enviro...","[{'code': '2', 'name': 'Public sector governan...","2,3,11"
479,[Social dev/gender/inclusion],"[{'code': '7', 'name': 'Social dev/gender/incl...","7,1"
480,[Public sector governance],"[{'code': '2', 'name': 'Public sector governan...","2,11"
481,"[Human development, Social dev/gender/inclusio...","[{'code': '8', 'name': 'Human development'}, {...","8,7,7,8"
482,"[Rural development, Environment and natural re...","[{'code': '10', 'name': 'Rural development'}, ...","10,11,11,10"
483,"[Environment and natural resources management,...","[{'code': '11', 'name': 'Environment and natur...","11,11,10,11"
484,"[Rural development, Financial and private sect...","[{'code': '10', 'name': 'Rural development'}, ...","10,4,7,10"
485,[Human development],"[{'code': '8', 'name': 'Human development'}, {...","8,4"
486,"[Public sector governance, Social protection a...","[{'code': '2', 'name': 'Public sector governan...","2,6,6,6"
487,"[Environment and natural resources management,...","[{'code': '11', 'name': 'Environment and natur...","11,10,10,11"
488,"[Human development, Public sector governance, ...","[{'code': '8', 'name': 'Human development'}, {...","8,2,2,8"
489,"[Urban development, Social protection and risk...","[{'code': '9', 'name': 'Urban development'}, {...","9,6,6,9"
490,"[Public sector governance, Public sector gover...","[{'code': '2', 'name': 'Public sector governan...","2,2"
491,[Rural development],"[{'code': '10', 'name': 'Rural development'}, ...","10,11"
492,"[Human development, Social dev/gender/inclusion]","[{'code': '8', 'name': 'Human development'}, {...","8,7"
493,[Environment and natural resources management],"[{'code': '11', 'name': 'Environment and natur...","11,5"
494,[Social protection and risk management],"[{'code': '6', 'name': 'Social protection and ...","6,8"
495,"[Financial and private sector development, Soc...","[{'code': '4', 'name': 'Financial and private ...","4,7"
496,"[Human development, Trade and integration, Pub...","[{'code': '8', 'name': 'Human development'}, {...","8,5,2,8"
497,[Rural development],"[{'code': '10', 'name': 'Rural development'}, ...","10,6"
498,"[Rural development, Rural development, Rural d...","[{'code': '10', 'name': 'Rural development'}, ...","10,10,10"
499,"[Urban development, Human development, Trade a...","[{'code': '9', 'name': 'Urban development'}, {...","9,8,5,4"

In [11]:
mjtheme_namecode = df['mjtheme_namecode']
code_name = {}
code_fre = {}
for i in mjtheme_namecode:
    for theme in i:
        if theme['code'] not in code_name:
            code_name[theme['code']] = theme['name']
            code_fre[theme['code']] = 1
        else:
            if code_name[theme['code']] == '' :
                code_name[theme['code']] = theme['name']
            code_fre[theme['code']] += 1
print(code_name)
print(code_fre)

{'8': 'Human development', '11': 'Environment and natural resources management', '1': 'Economic management', '6': 'Social protection and risk management', '5': 'Trade and integration', '2': 'Public sector governance', '7': 'Social dev/gender/inclusion', '4': 'Financial and private sector development', '10': 'Rural development', '9': 'Urban development', '3': 'Rule of law'}
{'8': 210, '11': 250, '1': 38, '6': 168, '5': 77, '2': 199, '7': 130, '4': 146, '10': 216, '9': 50, '3': 15}

In [12]:
import operator
code_fre_sortbyvalue = sorted(code_fre.items(), key=operator.itemgetter(1), reverse=True)
for key, value in code_fre_sortbyvalue:
    print('Theme '+ key + ' has ' + str(value) + ' frequencies.')

Theme 11 has 250 frequencies.
Theme 10 has 216 frequencies.
Theme 8 has 210 frequencies.
Theme 2 has 199 frequencies.
Theme 6 has 168 frequencies.
Theme 4 has 146 frequencies.
Theme 7 has 130 frequencies.
Theme 5 has 77 frequencies.
Theme 9 has 50 frequencies.
Theme 1 has 38 frequencies.
Theme 3 has 15 frequencies.

### Another way: get frequencies from themecode column

In [13]:
mjthemecode = df['mjthemecode'].str.split(',')

In [14]:
def fre_count(series):
    result = {}
    for row in series:
        for i in row:
            if i in result:
                result[i] += 1
            else:
                result[i] = 1
    return result

In [15]:
mjthemecode_fre = fre_count(mjthemecode)
mjthemecode_fre

{'1': 38,
 '10': 216,
 '11': 250,
 '2': 199,
 '3': 15,
 '4': 146,
 '5': 77,
 '6': 168,
 '7': 130,
 '8': 210,
 '9': 50}

In [16]:
import operator
mjthemecode_fre_sortbyvalue = sorted(mjthemecode_fre.items(), key=operator.itemgetter(1), reverse=True)
for key, value in mjthemecode_fre_sortbyvalue:
    print('Theme '+ key + ' has ' + str(value) + ' frequencies.')

Theme 11 has 250 frequencies.
Theme 10 has 216 frequencies.
Theme 8 has 210 frequencies.
Theme 2 has 199 frequencies.
Theme 6 has 168 frequencies.
Theme 4 has 146 frequencies.
Theme 7 has 130 frequencies.
Theme 5 has 77 frequencies.
Theme 9 has 50 frequencies.
Theme 1 has 38 frequencies.
Theme 3 has 15 frequencies.

So the top 10 major theme is 1 to 11 except 3. 
And the sequence from the most to less is 11, 10, 8, 2, 6, 4, 7, 5, 9, 1.

## Exercise 3. fill in the missing names

In [17]:
for i in mjtheme_namecode:
    for theme in i:
        if theme['name'] == '':
            theme['name'] = code_name[theme['code']]

print(mjtheme_namecode)

0      [{'code': '8', 'name': 'Human development'}, {...
1      [{'code': '1', 'name': 'Economic management'},...
2      [{'code': '5', 'name': 'Trade and integration'...
3      [{'code': '7', 'name': 'Social dev/gender/incl...
4      [{'code': '5', 'name': 'Trade and integration'...
5      [{'code': '6', 'name': 'Social protection and ...
6      [{'code': '2', 'name': 'Public sector governan...
7      [{'code': '11', 'name': 'Environment and natur...
8      [{'code': '10', 'name': 'Rural development'}, ...
9      [{'code': '2', 'name': 'Public sector governan...
10     [{'code': '10', 'name': 'Rural development'}, ...
11     [{'code': '10', 'name': 'Rural development'}, ...
12     [{'code': '4', 'name': 'Financial and private ...
13     [{'code': '5', 'name': 'Trade and integration'...
14     [{'code': '6', 'name': 'Social protection and ...
15     [{'code': '10', 'name': 'Rural development'}, ...
16     [{'code': '10', 'name': 'Rural development'}, ...
17     [{'code': '8', 'name': 'Human development'}, {...
18     [{'code': '8', 'name': 'Human development'}, {...
19     [{'code': '2', 'name': 'Public sector governan...
20     [{'code': '7', 'name': 'Social dev/gender/incl...
21     [{'code': '9', 'name': 'Urban development'}, {...
22     [{'code': '7', 'name': 'Social dev/gender/incl...
23     [{'code': '8', 'name': 'Human development'}, {...
24     [{'code': '10', 'name': 'Rural development'}, ...
25     [{'code': '11', 'name': 'Environment and natur...
26     [{'code': '4', 'name': 'Financial and private ...
27     [{'code': '11', 'name': 'Environment and natur...
28     [{'code': '10', 'name': 'Rural development'}, ...
29     [{'code': '7', 'name': 'Social dev/gender/incl...
                             ...
470    [{'code': '5', 'name': 'Trade and integration'...
471    [{'code': '10', 'name': 'Rural development'}, ...
472    [{'code': '11', 'name': 'Environment and natur...
473    [{'code': '11', 'name': 'Environment and natur...
474    [{'code': '9', 'name': 'Urban development'}, {...
475    [{'code': '4', 'name': 'Financial and private ...
476    [{'code': '10', 'name': 'Rural development'}, ...
477    [{'code': '4', 'name': 'Financial and private ...
478    [{'code': '2', 'name': 'Public sector governan...
479    [{'code': '7', 'name': 'Social dev/gender/incl...
480    [{'code': '2', 'name': 'Public sector governan...
481    [{'code': '8', 'name': 'Human development'}, {...
482    [{'code': '10', 'name': 'Rural development'}, ...
483    [{'code': '11', 'name': 'Environment and natur...
484    [{'code': '10', 'name': 'Rural development'}, ...
485    [{'code': '8', 'name': 'Human development'}, {...
486    [{'code': '2', 'name': 'Public sector governan...
487    [{'code': '11', 'name': 'Environment and natur...
488    [{'code': '8', 'name': 'Human development'}, {...
489    [{'code': '9', 'name': 'Urban development'}, {...
490    [{'code': '2', 'name': 'Public sector governan...
491    [{'code': '10', 'name': 'Rural development'}, ...
492    [{'code': '8', 'name': 'Human development'}, {...
493    [{'code': '11', 'name': 'Environment and natur...
494    [{'code': '6', 'name': 'Social protection and ...
495    [{'code': '4', 'name': 'Financial and private ...
496    [{'code': '8', 'name': 'Human development'}, {...
497    [{'code': '10', 'name': 'Rural development'}, ...
498    [{'code': '10', 'name': 'Rural development'}, ...
499    [{'code': '9', 'name': 'Urban development'}, {...
Name: mjtheme_namecode, dtype: object

In [18]:
def check_missing(series):
    for i in series:
        for theme in i:
            if theme['name'] == '':
                return True
    return False
            
print(check_missing(mjtheme_namecode))

False

In [19]:
df['mjtheme_namecode_new'] = mjtheme_namecode

In [20]:
df_new = df.drop(['mjtheme_namecode'], axis=1)
df_new.columns

Index(['_id', 'approvalfy', 'board_approval_month', 'boardapprovaldate',
       'borrower', 'closingdate', 'country_namecode', 'countrycode',
       'countryname', 'countryshortname', 'docty', 'envassesmentcategorycode',
       'grantamt', 'ibrdcommamt', 'id', 'idacommamt', 'impagency',
       'lendinginstr', 'lendinginstrtype', 'lendprojectcost',
       'majorsector_percent', 'mjsector_namecode', 'mjtheme', 'mjthemecode',
       'prodline', 'prodlinetext', 'productlinetype', 'project_abstract',
       'project_name', 'projectdocs', 'projectfinancialtype',
       'projectstatusdisplay', 'regionname', 'sector', 'sector1', 'sector2',
       'sector3', 'sector4', 'sector_namecode', 'sectorcode', 'source',
       'status', 'supplementprojectflg', 'theme1', 'theme_namecode',
       'themecode', 'totalamt', 'totalcommamt', 'url', 'mjtheme_namecode_new'],
      dtype='object')